# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optexp',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='optica.Paciente'),
        ),
    ]
