# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0002_auto_20160426_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[(b'mujer', b'Mujer'), (b'hombre', b'Hombre')], default=b'Mujer', max_length=10),
        ),
    ]
