# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0003_auto_20160426_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeo',
            name='armazon',
            field=models.CharField(choices=[('opcion1', 'Opcion1'), ('opcion2', 'Opcion2')], default='opcion1', max_length=50),
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='graduacion',
            field=models.CharField(choices=[('tuboGrande', 'TuboGrande'), ('TuboChico', 'tubochico')], default='TuboChico', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('opcion1', 'Opcion1'), ('opcion2', 'Opcion2')], default='opcion2', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], default='Mujer', max_length=10),
        ),
    ]
